getgenv().fastfetch = true;

local v1 = loadstring(game:HttpGet("https://raw.githubusercontent.com/3345-c-a-t-s-u-s/Kncrypt/refs/heads/main/Loader.lua"))()

if v1 == "BloxFruit.lua" then
    loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/1b350d82f2bb88bbe6d6cbf57555545b.lua"))()
elseif v1 == "Fisch.lua" then
    loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/aa742b594c5829798f5a6d810cc747a1.lua"))()
elseif v1 == "Doors.lua" then
    loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/91135bbe91694ad15eb3ae1d0ba3ed83.lua"))()
end;
